language: python
python:
  - 3.6

# install dependancies
install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database blog_db;' -U postgres
  - psql -c "CREATE USER zonecc WITH PASSWORD 'zonecc';" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source=blog  manage.py test  && coverage report -m
  - coveralls

after_success:
  - coveralls
