language: python
python:
  - 3.7

# install dependancies
install:
  - pipenv install

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database blogdb;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source='.' -m pytest auth*/apps/  && coverage report -m

after_success:
  - coveralls
