# Generated by Django 2.2.1 on 2019-05-16 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190516_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.TextField(default='', max_length=1000, validators=[django.core.validators.URLValidator]),
        ),
    ]
