# Generated by Django 2.2.1 on 2019-05-19 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20190516_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
