# Generated by Django 2.2.1 on 2019-05-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20190519_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
    ]
