# Generated by Django 2.2.1 on 2019-05-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_blogpost_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
