# Generated by Django 2.2.1 on 2019-05-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
