# Generated by Django 2.2.1 on 2019-05-12 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('other_names', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=60)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('year_of_birth', models.DateTimeField()),
                ('GUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 5, 12, 10, 30, 52, 909814, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
