# Generated by Django 2.2.1 on 2019-05-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190514_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_superuser',
        ),
    ]
